# failure-threshold: ignore
# no-fail: true


failure-threshold: ignore               # name of threshold level (error | warning | info | style | ignore | none)
# format: string                        # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | codacy)
ignored: DL3001                         # list of rules
label-schema:                           # See Linting Labels below for specific label-schema details
  author: Michael Buluma                # Your name
  contact: bulumaknight@gmail.com       # email address
  # created: timestamp                  # rfc3339 datetime
  # version: 1.0                        # semver
  # documentation: string               # url
  # git-revision: string                # hash
  # license: string                     # spdx
no-color: false                         # true | false
no-fail: true                           # true | false
# override:
  # error: [string]                     # list of rules
  # warning: [string]                   # list of rules
  # info: [string]                      # list of rules
  # style: [string]                     # list of rules
strict-labels: false                    # true | false
# trustedRegistries: string | [string]  # registry or list of registries
