---
name: ActiveMQ

on:
  push:
    paths:
      - 'activemq/**'
      - '.github/workflows/activemq.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a activemq/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a activemq/

    - name: Run in Dir above
      run: cd activemq && ls -a

    - name: Build the Docker image
      run: docker build . --file activemq/Dockerfile --tag docker-activemq-test:$(date +%s)
