---
name: ActiveMQ

on:
  push:
    paths:
      - 'activemq/**'
      - '.github/workflows/activemq.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a activemq/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a activemq/

    - name: Run in Dir above
      run: cd activemq && ls -a

    - name: Build the Docker image
      run: docker build . --file activemq/Dockerfile --tag docker-activemq-test:$(date +%s)

    - name: Create Issue on Build failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: ActiveMQ Build Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Lint check failed for commit ${{github.sha}}
