---
name: Caddy

on:
  push:
    paths:
      - 'caddy/**'
      - '.github/workflows/caddy.yaml'

jobs:
  # yamllint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: yamllint
  #       uses: ibiqlik/action-yamllint@v3

  #     - name: test dir
  #       run: ls -a caddy/

  build:

    runs-on: ubuntu-latest
    # needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a caddy/

    - name: Run in Dir above
      run: cd caddy && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      run: docker build . --file caddy/Dockerfile --tag docker-caddy-test:$(date +%s)
