---
name: Chrome Headless

on:
  push:
    paths:
      - 'chrome-headless/**'
      - '.github/workflows/chrome-headless.yaml'

  schedule:
    - cron: '0 2,5,7,9,12,14,18,20,22 * * *'
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: chrome-headless Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a chrome-headless/

    - name: Run in Dir above
      run: cd chrome-headless && ls -a

    - name: Build the Docker image
      run: cd chrome-headless && pwd && ls -a && docker build . --file Dockerfile --tag docker-chrome-headless-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: chrome-headless Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Lint check failed for commit ${{github.sha}}
