---
name: Chrome Headless

on:
  push:
    paths:
      - 'chrome-headless/**'
      - '.github/workflows/chrome-headless.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a chrome-headless/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a chrome-headless/

    - name: Run in Dir above
      run: cd chrome-headless && ls -a

    - name: Build the Docker image
      run: docker build . --file chrome-headless/Dockerfile --tag docker-chrome-headless-test:$(date +%s)
