---
name: Update Dockerfiles

on:
  schedule:
    - cron: '40 16 * * *'
jobs:
  deploy:
    name: Update Dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout the repository
        uses: actions/checkout@v2

      # - name: lint
      #   uses: luke142367/Docker-Lint-Action@v1.0.0
      #   with:
      #     target: Dockerfile
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📤 Update Dockerfiles
        uses: ludeeus/dockerfile-updater@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
