---
name: Kubectl

on:
  push:
    paths:
      - 'docker-kubectl/**'
      - '.github/workflows/docker-kubectl.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a docker-kubectl/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a docker-kubectl/

    - name: Run in Dir above
      run: cd docker-kubectl && ls -a

    - name: Build the Docker image
      run: docker build . --file docker-kubectl/Dockerfile --tag docker-kubectl-test:$(date +%s)
