---
name: Kubectl

on:
  push:
    paths:
      - 'docker-kubectl/**'
      - '.github/workflows/docker-kubectl.yaml'

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '30 * * * *'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a docker-kubectl/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Kubectl Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Kubectl Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a docker-kubectl/

    - name: Run in Dir above
      run: cd docker-kubectl && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      run: docker build . --file docker-kubectl/Dockerfile --tag docker-kubectl-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: Kubectl Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Kubectl Lint check failed for commit ${{github.sha}}
