name: Elastalert Image CI

on:
  push:
    paths:
      - 'elastalert/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file elastalert/Dockerfile --tag docker-test:$(date +%s)
