name: FPM Image CI

on:
  push:
    paths:
      - 'fpm/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file fpm/Dockerfile --tag docker-test:$(date +%s)
