---
name: Influx

on:
  push:
    paths:
      - 'influx/**'
      - '.github/workflows/influx.yaml'

  schedule:
    - cron: '0 2,5,7,9,12,14,18,20,22 * * *'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a influx/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: influx Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a influx/

    - name: Run in Dir above
      run: cd influx && ls -a

    - name: Build the Docker image
      # run: docker build . --file john/Dockerfile --tag docker-john-test:$(date +%s)
      run: cd influx && pwd && ls -a && docker build . --file Dockerfile --tag docker-influx-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: influx Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: influx - Build failed for commit ${{github.sha}}
