---
name: Jira

on:
  push:
    paths:
      - 'jira/**'
      - '.github/workflows/jira.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a jira/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a jira/

    - name: Run in Dir above
      run: cd jira && ls -a

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-test:$(date +%s)
