---
name: 1. Make Test

# This runs every day on 1801 UTC
on:
  push:
    paths:
      # - 'spotify/**'
      - '.github/workflows/make.yml'

  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate Github
        uses: actions/labeler@v3.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@master
        with:
          fetch-depth: '2'
      - name: make test
        # run: make test
        run: make dockerfiles
        # run: make build
        # run: make latest-versions
        # run: make image DIR=influxdb-grafana
        # run: make run DIR=traceroute
        shell: bash
        
      - name: Collect docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: failure()
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: logs.tgz
          path: ./logs.tgz
