on:
  push
name: make test
jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@master
        with:
          fetch-depth: '2'
      - name: make test
#         run: make test
        # run: make dockerfiles
#         run: make build
        # run: make latest-versions
        run: make run github-dev
        shell: bash
