---
name: Mattermost

on:
  push:
    paths:
      - 'mattermost/**'
      - '.github/workflows/mattermost.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a mattermost/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a mattermost/

    - name: Run in Dir above
      run: cd mattermost && ls -a

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-mattermost-test:$(date +%s)
