---
name: Puppeteer-Base

on:
  push:
    paths:
      - 'puppeteer-base/**'
      - '.github/workflows/puppeteer-base.yaml'

  schedule:
    - cron: '0 2,5,7,9,12,14,18,20,22 * * *'
  workflow_dispatch:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a puppeteer-base/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Puppeteer-Base Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Puppeteer-Base Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a puppeteer-base/

    - name: Run in Dir above
      run: cd puppeteer-base && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      run: docker build . --file puppeteer-base/Dockerfile --tag docker-puppeteer-base-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: Puppeteer-Base Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Puppeteer-Base build failed for commit ${{github.sha}}
  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: puppeteer-base/
          file: puppeteer-base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ github.repository }}:latest
