---
name: Teleport

on:
  push:
    paths:
      - 'teleport/**'
      - '.github/workflows/teleport.yaml'

  schedule:
    - cron: '0 2,5,7,9,12,14,18,20,22 * * *'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a teleport/

      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Teleport Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Teleport Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a teleport/

    - name: Run in Dir above
      run: cd teleport && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      # run: docker build . --file teleport/Dockerfile --tag docker-teleport-test:$(date +%s)
      run: cd teleport && pwd && ls -a && docker build . --file Dockerfile --tag docker-teleport-test:$(date +%s)

    - name: Create Issue on Build failure.
      if: failure()
      uses: buluma/create-issue-action@v2.0.0
      with:
        title: Teleport Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: bug
        body: Teleport build failed for commit ${{github.sha}}
