name: Jira Image CI

on:
  push:
    paths:
      - 'jira/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file teleport/Dockerfile --tag docker-test:$(date +%s)
