---
name: Telnet

on:
  push:
    branches:
      - main
    paths:
      - 'telnet/**'
      - '.github/workflows/telnet.yml'

  schedule:
    - cron: '0 2,5,7,9,12,14,18,20,22 * * *'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a telnet/
        
      - name: Create Issue on Lint failure.
        if: failure()
        uses: buluma/create-issue-action@v2.0.0
        with:
          title: Telnet Lint Test Failed
          token: ${{secrets.GITHUB_TOKEN}}
          assignees: ${{github.actor}}
          labels: bug
          body: Telnet Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a telnet/

    - name: Run in Dir above
      run: cd telnet && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      run: cd telnet && pwd && ls -a && docker build . --file Dockerfile --tag docker-telnet:$(date +%s)
