---
name: Time-Machine

on:
  push:
    paths:
      - 'time-machine/**'
      - '.github/workflows/time-machine.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a time-machine/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a time-machine/

    - name: Run in Dir above
      run: cd time-machine && ls -a

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-time-machine-test:$(date +%s)
