name: Tor Image CI

on:
  push:
    paths:
      - 'tor/Dockerfile'

jobs:
  yamllint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file tor/Dockerfile --tag docker-test:$(date +%s)
