---
name: vagrant

on:
  push:
    paths:
      - 'vagrant/**'
      - '.github/workflows/vagrant.yaml'

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3

      - name: test dir
        run: ls -a vagrant/

  build:

    runs-on: ubuntu-latest
    needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a vagrant/

    - name: Run in Dir above
      run: cd vagrant && ls -a

    - name: Build the Docker image
      run: docker build . --file vagrant/Dockerfile --tag docker-vagrant-test:$(date +%s)
