---
name: Zookeeper

on:
  push:
    paths:
      - 'zookeeper/**'
      - '.github/workflows/zookeeper.yaml'

  schedule:
    - cron: '30 * * * *'

jobs:
#   yamllint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: yamllint
#         uses: ibiqlik/action-yamllint@v3

#       - name: test dir
#         run: ls -a zookeeper/

#       - name: Create Issue on Lint failure.
#         if: failure()
#         uses: buluma/create-issue-action@v2.0.0
#         with:
#           title: zookeeper Lint Test Failed
#           token: ${{secrets.GITHUB_TOKEN}}
#           assignees: ${{github.actor}}
#           labels: bug
#           body: zookeeper Lint check failed for commit ${{github.sha}}

  build:

    runs-on: ubuntu-latest
#     needs: yamllint

    steps:
    - uses: actions/checkout@v2
    - name: test dir
      run: ls -a zookeeper/

    - name: Run in Dir above
      run: cd zookeeper && ls -a

    - name: Where are we
      run: pwd && ls -a

    - name: Build the Docker image
      # run: docker build . --file jira/Dockerfile --tag docker-jira-test:$(date +%s)
      run: cd zookeeper && pwd && ls -a && docker build . --file Dockerfile --tag docker-zookeeper-test:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push image.
      run: |
        # Push $php_version tag.
        docker push buluma/zookeeper:3.4.13

        # Push latest tag if building latest version.
        docker tag buluma/php-apache:${{ matrix.php_version }} buluma/php-apache:latest
          docker push buluma/php-apache:latest

#     - name: Create Issue on Build failure.
#       if: failure()
#       uses: buluma/create-issue-action@v2.0.0
#       with:
#         title: zookeeper Build Failed
#         token: ${{secrets.GITHUB_TOKEN}}
#         assignees: ${{github.actor}}
#         labels: bug
#         body: zookeeper build failed for commit ${{github.sha}}
